module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "border-white": "var(--border-white)",
        "eduport-color24292d-dark": "var(--eduport-color24292d-dark)",
        "eduport-coloreduport-body-color":
          "var(--eduport-coloreduport-body-color)",
        "eduport-coloreduport-danger-soft":
          "var(--eduport-coloreduport-danger-soft)",
        "eduport-coloreduport-orange": "var(--eduport-coloreduport-orange)",
        "gray-colorsgray-dark": "var(--gray-colorsgray-dark)",
        "soft-colorbody": "var(--soft-colorbody)",
        "soft-colordanger": "var(--soft-colordanger)",
        "soft-colorinfo": "var(--soft-colorinfo)",
        "soft-colororange": "var(--soft-colororange)",
        "soft-colorprimary": "var(--soft-colorprimary)",
        "soft-colorpurple": "var(--soft-colorpurple)",
        "soft-colorsecondary": "var(--soft-colorsecondary)",
        "soft-colorsuccess": "var(--soft-colorsuccess)",
        "soft-colorwarning": "var(--soft-colorwarning)",
        "theme-colorblue": "var(--theme-colorblue)",
        "theme-colorbody": "var(--theme-colorbody)",
        "theme-colorbutton-light": "var(--theme-colorbutton-light)",
        "theme-colordanger": "var(--theme-colordanger)",
        "theme-colordark": "var(--theme-colordark)",
        "theme-colorinfo": "var(--theme-colorinfo)",
        "theme-colorlight": "var(--theme-colorlight)",
        "theme-colororange": "var(--theme-colororange)",
        "theme-colorprimary": "var(--theme-colorprimary)",
        "theme-colorpurple": "var(--theme-colorpurple)",
        "theme-colorsecondary": "var(--theme-colorsecondary)",
        "theme-colorsuccess": "var(--theme-colorsuccess)",
        "theme-colorwarning": "var(--theme-colorwarning)",
        "theme-colorwhite": "var(--theme-colorwhite)",
        warning: "var(--warning)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-a-tag": "var(--body-a-tag-font-family)",
        "body-body-text": "var(--body-body-text-font-family)",
        "body-button-text": "var(--body-button-text-font-family)",
        "body-h6-fw-500": "var(--body-h6-fw-500-font-family)",
        "body-nav-text": "var(--body-nav-text-font-family)",
        "body-p-h6-text": "var(--body-p-h6-text-font-family)",
        "body-small": "var(--body-small-font-family)",
        "display-text-display-1": "var(--display-text-display-1-font-family)",
        "heading-text-h1": "var(--heading-text-h1-font-family)",
        "heading-text-h2": "var(--heading-text-h2-font-family)",
        "heading-text-h3": "var(--heading-text-h3-font-family)",
        "heading-text-h4": "var(--heading-text-h4-font-family)",
        "heading-text-h5": "var(--heading-text-h5-font-family)",
        "heading-text-h6": "var(--heading-text-h6-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
